### ISSUE TITLE
Autostart on join

### ISSUE THREAD

**Issue by ElliotS2007** [exaroton/exaroton-velocity#2]
It would be really cool to have an option to autostart a specified backend server when a player tries to join the proxy. This could be beneficial because it could allow the proxy to run for longer and then make the unused backend servers shutdown when not in use. It could also be cool to autostart a backend when using the switch command

**Comment by JulianVennen** [comment]
We considered implementing this but I think the problem was that the bungee/velocity API didn't have any events that triggered before a working server was required.

There is however a different way:
1. Set your proxy server to start and stop automatically
2. Set your backen/lobby server to not stop automatically
3. Configure the proxy to automatically start and stop the backend server with it.
